variable "vpc-id" {}
variable "ec2_security_groups" {}
variable "rds_allocated_storage" {}
variable "rds_engine" {}
variable "rds_engine_version" {}
variable "rds_subnet_group" {}
variable "instance_class" {}
variable "database_name" {}
variable "database_user" {}
